export enum ActionTypes {
    USER_SET = 'USER_SET',
    USER_CLEAR = 'USER_CLEAR',
    IMAGES_GET = 'IMAGES_GET',
    IMAGES_CLEAR = 'IMAGES_CLEAR',
    IMAGES_LIKE = 'IMAGES_LIKE',
    HISTORY_GET = 'HISTORY_GET',
    HISTORY_SET = 'HISTORY_SET',
    HISTORY_CLEAR = 'HISTORY_CLEAR',
    THEME_SET = 'THEME_SET',
    THEME_CLEAR = 'THEME_CLEAR',
    LOADING_SET = 'LOADING_SET',
    LOADING_CLEAR = 'LOADING_CLEAR'
}
